#!/bin/bash
# set -x
#---IFS store value---#
OLDIFS=$IFS

#---Usage---#
usage(){
echo "$0, $1 needs to be a valid path to a .*.mxf.csv file generated by ARRIMetaExtract.sh"
echo "$2 needs to be a string for each field is separated by \":\""
exit
}

INPUTCSV=$1
NOMENCLATURE=$2

#---validation----#
[[ "$INPUTCSV" =~ .*\.mxf\.csv ]]
META=$(echo $INPUTCSV)
#----STRING MANIPULATION----#
METAFIRSTLINE=$(cat "$META" | head -n 1)
METASECONDLINE=$(cat "$META" | head -n 2 | tail -n 1)
FILENAME=""
IFS=$':'
for var in $NOMENCLATURE
do
  if [[ "$METAFIRSTLINE" =~ \;$var\; ]]; then
    ((i=1))
    while [[ $(echo "$METAFIRSTLINE" | cut -d ";" -f $i ) != "$var" ]]
    do
      ((i++))
    done
    VALUE=$(echo "$METASECONDLINE" | cut -d ";" -f $i | tr ":" "x" | sed "s/\([0-9]*\)\.0*/\1/" | tr " " "-" )
    FILENAME="$FILENAME$VALUE"
  
  else
  FILENAME="$FILENAME$var"
  fi    
done
IFS=$OLDIFS
echo "$FILENAME"